### ISSUE TITLE
Add Cluster as Release: Vinyl track numbers not supported

### ISSUE THREAD

**Issue by ghlupe2** [metabrainz/picard-plugins#46]
When I try to add a 10 LP release with alphanumerical track numbers like 1.A1, 1.A2, 1.B1, 1.B2, 1.B3, 2.C1, 2.C2, 2.D1 ... and so on, I get an error on the MB page:

The data you’ve seeded contained the following errors:
mediums.1.track.0 isn’t defined, do your indexes start at 0?
mediums.2.track.0 isn’t defined, do your indexes start at 0?
mediums.3.track.0 isn’t defined, do your indexes start at 0?
mediums.4.track.0 isn’t defined, do your indexes start at 0?
mediums.5.track.0 isn’t defined, do your indexes start at 0?
mediums.6.track.0 isn’t defined, do your indexes start at 0?
mediums.7.track.0 isn’t defined, do your indexes start at 0?
mediums.8.track.0 isn’t defined, do your indexes start at 0?
mediums.9.track.0 isn’t defined, do your indexes start at 0?
Review the documentation on release editor seeding and make sure your data is formatted correctly.

The tracks get created well but the numbering isn't alphanumerical and from Medium 2 on leading empty tracks are created.

**Comment by zas** [comment]
Please be sure to specify to which plugin the issue is related, since we have many plugins in this repo.

**Comment by ghlupe2** [comment]
It is "Add Cluster as Release" version 0.7

**Comment by mineo** [comment]
AFAIK seeding the release editor with vinyl track numbers, so this should maybe fall back to just creating numbers 1-x for each medium.

**Comment by phw** [comment]
This has been addressed with the add cluster as release functionality being integrated into Picard itself, see https://github.com/metabrainz/picard/pull/1839 . The current plugin will stay around for the next one or two minor releases, but the goal is to move users to the built-in functionality staring with the next release Picard 2.7.

The way this works is that the displayed track number gets submitted independent from the numeric order of tracks. See the below screenshot:

![grafik](https://user-images.githubusercontent.com/29852/124467125-b916a000-dd97-11eb-9a58-073f04d655e6.png)
