### ISSUE TITLE
last.fm api change

### ISSUE THREAD

**Issue by monkiibiz** [metabrainz/picard-plugins#54]
Last.fm's API has changed - the current plugins (last.fm and last.fm.plus) utilizes the /1.0/ service, which no longer exists:

E: 11:52:14 Network request error for http://ws.audioscrobbler.com:80/1.0/track/38%2520Special/Back%2520Alley%2520Sally/toptags.xml: Error downloading http://ws.audioscrobbler.com:80/1.0/track/38%252520Special/Back%252520Alley%252520Sally/toptags.xml - server replied: Not Found (QT code 203, HTTP code 404)

New API documentation: 
http://www.last.fm/api/intro

Plugins should be rewritten to utilize the new methods
artist.getTopTags http://www.last.fm/api/show/artist.getTopTags
track.getTopTags http://www.last.fm/api/show/track.getTopTags

**Comment by monkiibiz** [comment]
Seems to be addressed in https://github.com/metabrainz/picard-plugins/pull/39 and https://github.com/metabrainz/picard-plugins/pull/50 - any chance to get these merged?

**Comment by pdf** [comment]
Looks like both PRs have been closed, so I guess the `lastfm` and `lastfmplus` plugins will remain broken for the foreseeable future.
