### ISSUE TITLE
Add Cluster as Release: Musicbrainz mirror

### ISSUE THREAD

**Issue by TrueOsiris** [metabrainz/picard-plugins#59]
In the musicbrainz picard settings, I'm pointing to my own musicbrainz mirror.
For this plugin however, this server should not be used, since releases can only be added directly on musicbrainz.org.

I've seen a closed & patched issue about the exact opposite of this, which I do not understand.
Releases should be added on the main database, not on mirrors or copys.
Perhaps a config checkbox is in order to chose between musicbrainz.org and the configured server?

**Comment by phw** [comment]
This will be addressed by the "add cluster as release" functionality being moved into Picard itself. See related pull requests https://github.com/metabrainz/picard/pull/1839 and https://github.com/metabrainz/picard/pull/1843 , the later specifically dealing with the issue of which server to use.
