### ISSUE TITLE
New plugin: fetch genre(s) from Wikidata

### ISSUE THREAD

**Issue by Freso** [metabrainz/picard-plugins#61]
It would be cool with a plugin to look up genres from [Wikidata](https://www.wikidata.org/). A lot of MusicBrainz entities have Wikidata URL relationships that could be used to look for the [genre property (P136)](https://www.wikidata.org/wiki/Property:P136).

Inspired by https://community.metabrainz.org/t/plugin-that-scrapes-genre-from-wikipedia/148728?u=freso

See also https://github.com/beetbox/beets/issues/2227

**Comment by dns53** [comment]
Querying the genre's associated with moby
https://musicbrainz.org/artist/8970d868-0723-483b-a75b-51088913d3d4

This links to the wikidata entry:
https://www.wikidata.org/wiki/Q14045

To get this in json format you can change the url to the following format:
https://www.wikidata.org/wiki/Special:EntityData/Q14045.json

Wikidata is built on "snarks" these are property equals value style statements
look for the property we want, in our case this is property P136.
There are snarks returned with the first Q170611.
If you then look up https://www.wikidata.org/wiki/Special:EntityData/Q170611.json this will be "Techno" 
You can get a localised string as well as other information such as wikipedia pages etc. 

P136: [
{
mainsnak: {
snaktype: "value",
property: "P136",
datavalue: {
value: {
entity-type: "item",
numeric-id: 170611,
id: "Q170611"
},
type: "wikibase-entityid"
},
datatype: "wikibase-item"
},
.....
]


There are most likely better ways of querying this data as there are python libraries for wikidata. 

It may be easier to write a sparql query that returns the list of properties we want using https://query.wikidata.org/
I cannot understand sparql  enough to get this working.

**Comment by Sophist-UK** [comment]
A good starting point for this would be my Artist Website plugin - which has all the functionality needed (except JSON parsing since musicbrainz returns xml). So it has asynchronous web service calls and caching.

The only other thing you would need to do is deal with Album vs. Track genres. Obviously all metadata is stored in individual track files, but I suspect that most (if not all) Wikipedia Genres are Album genres.

**Comment by dns53** [comment]
I have made some progress.
Testing based on the following release group.
https://musicbrainz.org/release-group/f92554b1-c6af-4929-8560-717f0a717ec7

Determining the wikidata url is straight forward by looking up the release group and finding the url like in the artist website plugin.
This links to http://www.wikidata.org/entity/Q21198282
I then request the wikidata entry using the following format to request RDF.
https://www.wikidata.org/wiki/Special:EntityData/Q21198282.rdf
You need to get the second Description tag like the below.
See if there is a property P136 tag in there and you want the resource attribute as this represents the genre you want.
Further down in the RDF document there is the entry for Q188994 that represents our genre in wikidata.
This contains strings for each locale for that genre so in this case it is "drum and bass" as the string we want.

<RDF>
...
	<rdf:Description rdf:about="http://www.wikidata.org/entity/Q21198282">
...
		<wdt:P136 rdf:resource="http://www.wikidata.org/entity/Q188994"/>
...
       </rdf:Description>
..
	<rdf:Description rdf:about="http://www.wikidata.org/entity/Q188994">
...
		<rdfs:label xml:lang="en">drum and bass</rdfs:label>
..
	</rdf:Description>

**Comment by dns53** [comment]
Plugin added as pull request  #63 
Please test and give feedback.
This is the first useful bit of python i have written so please offer style suggestions etc as I probably do not know a better way to do things.
It seems to work but is highly likely to have bugs

**Comment by dns53** [comment]
I think the current version is good enough to be merged.
What needs to be done before this can happen?

**Comment by lkzkk** [comment]
I gave it a shot using this example: https://www.wikidata.org/wiki/Q577717 and it did tell me it's Indie Pop.

Since there is no genre defined in the item itself, I'm guessing it pulled it from one of the linked databases (Discogs?). Discogs however lists two genres and two styles: https://www.discogs.com/master/9537. 

In such cases souldn't it pull all the genres/styles and save them as a multi-value tag?

**Comment by dns53** [comment]
It looks at the release group, artist or work with a corresponding wikidata item.
In your case there is no genre on the release group but there is one on the artist https://www.wikidata.org/wiki/Q1239214 and this has the genre tag set to "indie pop".

I'm not currently looking at discogs for genre tags but they do have an api.
For the discogs link https://www.discogs.com/master/9537
you can call the api https://api.discogs.com/masters/9537
This has a styles entry containing the genre tags.

It is something that I could potentially add in the future but probably not any time soon.

**Comment by lkzkk** [comment]
oh, that makes more sense. thanks for the explanation!
