### ISSUE TITLE
Plugin featartistsintitles leaves feat. artists in sort tags

### ISSUE THREAD

**Issue by hoxia** [metabrainz/picard-plugins#62]
Plugin featartistsintitles (and also featartists) isn't changing (eg truncating) artistsort and albumartistsort tags, leaving featured artists in these tags but not in the artist and albumartist tags themselves. Neither of these plugins touch the sort tags at all.

Link to specific plugin: https://github.com/metabrainz/picard-plugins/tree/master/plugins/featartistsintitles
Discussion on Musicbrainz forum: https://community.metabrainz.org/t/feat-artists-in-titles-plugin-leaves-featured-artists-in-sort-tags/144600

**Comment by NobahdiAtoll** [comment]
its easy enough to modify (if you know python, and even if not if you have common sense) but i do think this should be addressed. Personally I completely remove featured artists and let the "artists" tag handle multiple artists the script is available for download [Here](https://github.com/NobahdiAtoll/MusicBrainzPicardPlugins)
