### ISSUE TITLE
Album Artist Website and MB 500/503 errors

### ISSUE THREAD

**Issue by Sophist-UK** [metabrainz/picard-plugins#76]
If the web call fails, ideally Picard would requeue it (and this functionality is planned).

However until this is in place, the impact of these on this plugin is greater than on Picard for e.g. release lookups because it changes the metadata for every track in albums by these artists.

If the Picard retry functionality is not forthcoming by the time 1.4 is released, I may need to add similar functionality to this plugin.

**Comment by mineo** [comment]
Is this unique to the album artist website plugin or does it apply to others that make HTTP calls (acousticbrainz, lastfm, wikidata, ...) as well?

**Comment by Sophist-UK** [comment]
Someone (@samj912?) was working on a Picard PR to retry web calls that fail with a 503, however they got bogged down in a restructure of the webservice classes and a simpler PR is needed for 1.4. 

To put this in context, I am seeing 5%-10% of album loads fail with 503s. But user can manually retry the album load fail - they cannot manually retry MB web service calls made by plugins except (perhaps) by reloading the album that called the plugin that made the webservice call that lived in the house that jack built.

But if this is done in Picard itself, plugins won't need to worry about it.

THAT SAID, the Picard code is to solve getting 503s from MB where we don't need to throttle back the webservice call rate because MB infrastructure can cope with generating a lot of 503s. That may not be the case for other servers like acousticbrainz, lastfm, wikidata etc. 

Also, MB guidelines are that MB data doesn't change that frequently, and clients should avoid making repeated calls for the same data in order to keep loads down. I proposed that my rejected PR to improve QT caching by Picard is reincarnated and enhanced so that:

1. if cache age is < (say) a week or a day, then we use the cache without an MB call EXCEPT if this is a refresh; if we use the entry in the QT cache without a call, then not only do we not wait for the MB response, but we can also queue the next MB call immediately and not be rate limited;

2. if cache age is more than this or its a refresh, then we make the call as usual and let the result be cached.

I would imagine that lastFm and acousticbrainz data is equally static, and so presumably the same rules will apply - though we will need a way for plugins / Picard webservice code to be able to know that the album is being manually refreshed.

This would reduce the load on the server from Picard and make it a good citizen - though the Kodi folks say it is their software which is causing exponential growth in calls so unless Kodi implements caching along the same lines, then reducing the Picard load will probably not make much difference overall.

**Comment by phw** [comment]
Request retry on 503 had been implemented with PICARD-807 for Picard 2.0. I close this issue.
