### ISSUE TITLE
Add Cluster As Release: HTTPS redirection loses form data on MusizBrainz.org

### ISSUE THREAD

**Issue by AltarBeastiful** [metabrainz/picard-plugins#77]
When posting the form data to MusizBrainz.org, the plugin gets redirected from HTTP to HTTPS, losing the form data in the process.

The plugin should post to MusizBrainz on HTTPS as it is the preferred method to interact with the website.

This can be manually fixed by setting the server port to 443, but the default to 80 actually breaks this plugin.

I don't see a good way to guess if we can use https other than port without breaking compatibility for local server not using https. Should we ask for a change in the default settings of picard?

**Comment by Sophist-UK** [comment]
https://github.com/metabrainz/picard/pull/600 has already been proposed for this.

**Comment by mineo** [comment]
This has already been reported as [PICARD-693](https://tickets.metabrainz.org/browse/PICARD-963) and is not fixed by the pull request mentioned above.

**Comment by Freso** [comment]
How will PICARD-693 not be fixed by #600?

**Comment by AltarBeastiful** [comment]
https://github.com/metabrainz/picard/pull/600 fixes `build_qurl` but the plugin doesn't use it. 
This question has just been answered [in the official ticket](https://tickets.metabrainz.org/browse/PICARD-963?focusedCommentId=41989&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-41989). 

Closing as a duplicate of [PICARD-963](https://tickets.metabrainz.org/browse/PICARD-963).
