### ISSUE TITLE
Plugin Idea: Access custom tags from files with tagger-script

### ISSUE THREAD

**Issue by rezeptpflichtig** [metabrainz/picard-plugins#82]
I'd like to have a plugin that can make any custom tag that is present in the files available in tagger-script. So that $getcustomtag(whatever) returns the value for that custom tag if it is present.

Is this possible with a plugin?
If yes, as I am not a coder and I am not familiar with the plugin system in picard, how would I tackle this problem? The plugin API page [1] didn't help me..
Would this be done via "from picard.file import File"?

I would be grateful about any information I could get about this matter.

[1] https://picard.musicbrainz.org/docs/plugin-api/

**Comment by Sophist-UK** [comment]
I am not sure what's to start here. 

At present Picard already supports custom tags without a plugin though IIRC support for custom tags depends to some extent on the file format you are using. 

There are currently no hooks to allow you to use plugins to enhance the functions of a specific file format.

And writing a plugin requires coding - and your lack of coding knowledge is (I am afraid) somewhat obvious from your complete  misunderstanding of the python import statement. 

I would suggest you read the help pages on the Picard web site about tags to see if that will help you understand more about existing support for custom tags. 

P. S. Github is not the place to ask "how do I..." questions. Please use the community forums.

**Comment by rezeptpflichtig** [comment]
sorry, I will ask this this in the metabrainz forum.
