### ISSUE TITLE
Suggestion: Implement Travis and unit testing for plugin PRs.

### ISSUE THREAD

**Issue by Sophist-UK** [metabrainz/picard-plugins#91]

**Comment by Sophist-UK** [comment]
I note that we have Travis tests, however they run both Py2 and Py3 tests, and plugins may not work correctly on both.

So we need to run Travis tests for Picard v1 plugins on Py2 / 1.4.x branch of Picard and Picard v2 plugins on Py3 / master branch.

**Comment by Sophist-UK** [comment]
P.S. Travis also runs Py3.4 tests - not sure why as Py3,4 is not supported for Picard v2.

**Comment by phw** [comment]
I am closing this, as we do run the tests on Github Actions.
